api_key: ""
training_data: "training.txt"
waiting_messages:
  - "<gradient:#1E90FF:#87CEFA>Tebet</gradient> <gray>>> <reset>我正在矿洞深处挖掘，稍等片刻，我会回来的。"
  - "<gradient:#1E90FF:#87CEFA>Tebet</gradient> <gray>>> <reset>正在搜寻一些钻石，别急，我很快就会回复你。"
  - "<gradient:#1E90FF:#87CEFA>Tebet</gradient> <gray>>> <reset>啊，刚碰到了一群僵尸，稍等我一下！"
  - "<gradient:#1E90FF:#87CEFA>Tebet</gradient> <gray>>> <reset>对不起，我正在农田里劳作，请稍后再联系我。"
  - "<gradient:#1E90FF:#87CEFA>Tebet</gradient> <gray>>> <reset>我正在修建我的小屋，需要一些时间完成。"
  - "<gradient:#1E90FF:#87CEFA>Tebet</gradient> <gray>>> <reset>哎呀，我的稿斧断了，需要找一些铁来修理它。"
  - "<gradient:#1E90FF:#87CEFA>Tebet</gradient> <gray>>> <reset>正在河边钓鱼，让我再试一次，很快就回来。"
  - "<gradient:#1E90FF:#87CEFA>Tebet</gradient> <gray>>> <reset>我被一群鸡包围了，正在收集鸡蛋，稍等片刻。"
